"""Write src/two_much_two_read/chinese_script_table.py from OpenCC's character dictionaries.

    uv run --with opencc-python-reimplemented python scripts/generate_chinese_script_table.py

OpenCC (https://github.com/BYVoid/OpenCC, Apache License 2.0) lists, for each character, the
characters it may be written as in the other script. A character that lists no use of itself there
is written only in its own script: 扩 is Simplified alone, while 台, 了 and 合, which Traditional
text writes as they are, belong to both. One whose Taiwan form is itself belongs to both as well
(峯 is 峰 in Taiwan, so 峰 is no sign of Simplified). These sets only say which text needs
converting; the conversion itself is zhconv-rs's, which reads phrases rather than characters.
"""

from __future__ import annotations

import argparse
from pathlib import Path

HEADER = '''"""Characters written in only one Chinese script, which mark text as needing conversion.

Generated by scripts/generate_chinese_script_table.py from OpenCC's STCharacters, TSCharacters and
TWVariants (https://github.com/BYVoid/OpenCC, Apache License 2.0). Do not edit by hand.
"""

'''
CHUNK = 100


def _table(path: Path) -> dict[str, list[str]]:
    table: dict[str, list[str]] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        if "\t" in line and not line.startswith("#"):
            key, values = line.split("\t", 1)
            table[key] = values.split()
    return table


def _only_in_own_script(table: dict[str, list[str]], variants: dict[str, list[str]]) -> str:
    characters = []
    for character, candidates in sorted(table.items()):
        forms = {form for candidate in candidates for form in variants.get(candidate, [candidate])}
        if len(character) == 1 and character not in candidates and character not in forms:
            characters.append(character)
    return "".join(characters)


def _constant(name: str, characters: str) -> str:
    chunks = [characters[index : index + CHUNK] for index in range(0, len(characters), CHUNK)]
    return f"{name} = (\n" + "".join(f'    "{chunk}"\n' for chunk in chunks) + ")\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--dictionary", type=Path, help="OpenCC's dictionary directory; found in the opencc package if omitted")
    parser.add_argument("--output", type=Path, default=Path("src/two_much_two_read/chinese_script_table.py"))
    args = parser.parse_args()
    dictionary = args.dictionary
    if dictionary is None:
        import opencc  # type: ignore[import-not-found]

        dictionary = Path(opencc.__file__).parent / "dictionary"
    simplified_only = _only_in_own_script(_table(dictionary / "STCharacters.txt"), _table(dictionary / "TWVariants.txt"))
    traditional_only = _only_in_own_script(_table(dictionary / "TSCharacters.txt"), {})
    args.output.write_text(
        HEADER
        + "# Written only in Simplified Chinese: text holding one is converted for a Traditional digest.\n"
        + _constant("SIMPLIFIED_ONLY", simplified_only)
        + "\n# Written only in Traditional Chinese: text holding one is converted for a Simplified digest.\n"
        + _constant("TRADITIONAL_ONLY", traditional_only),
        encoding="utf-8",
    )
    print(f"{len(simplified_only)} Simplified-only, {len(traditional_only)} Traditional-only")


if __name__ == "__main__":
    main()
