"""Write src/two_much_two_read/chinese_script_table.py from OpenCC's character dictionaries.

    uv run --with opencc-python-reimplemented python scripts/generate_chinese_script_table.py

OpenCC (https://github.com/BYVoid/OpenCC, Apache License 2.0) lists, for each character, the
characters it may be written as in the other script. Only a character that lists no use of itself
there is replaced: 扩 becomes 擴, while 台, 了 and 合, which Traditional text writes as they are,
stay. A replacement that Taiwan writes differently from OpenCC's standard form takes Taiwan's (峯
is 峰), and one that comes back as the character it started from is dropped.
"""

from __future__ import annotations

import argparse
from pathlib import Path

HEADER = '''"""Characters written only in one Chinese script, each paired with its form in the other.

Generated by scripts/generate_chinese_script_table.py from OpenCC's STCharacters, TSCharacters and
TWVariants (https://github.com/BYVoid/OpenCC, Apache License 2.0). Do not edit by hand.
"""

'''
CHUNK = 50


def _table(path: Path) -> dict[str, list[str]]:
    table: dict[str, list[str]] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        if "\t" in line and not line.startswith("#"):
            key, values = line.split("\t", 1)
            table[key] = values.split()
    return table


def _pairs(table: dict[str, list[str]], variants: dict[str, list[str]]) -> str:
    pairs = []
    for character, candidates in sorted(table.items()):
        if len(character) != 1 or character in candidates:
            continue
        replacement = variants.get(candidates[0], candidates)[0]
        if len(replacement) == 1 and replacement != character:
            pairs.append(character + replacement)
    return "".join(pairs)


def _constant(name: str, pairs: str) -> str:
    chunks = [pairs[index : index + CHUNK * 2] for index in range(0, len(pairs), CHUNK * 2)]
    return f"{name} = (\n" + "".join(f'    "{chunk}"\n' for chunk in chunks) + ")\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--dictionary", type=Path, help="OpenCC's dictionary directory; found in the opencc package if omitted")
    parser.add_argument("--output", type=Path, default=Path("src/two_much_two_read/chinese_script_table.py"))
    args = parser.parse_args()
    dictionary = args.dictionary
    if dictionary is None:
        import opencc  # type: ignore[import-not-found]

        dictionary = Path(opencc.__file__).parent / "dictionary"
    taiwan = _table(dictionary / "TWVariants.txt")
    to_traditional = _pairs(_table(dictionary / "STCharacters.txt"), taiwan)
    to_simplified = _pairs(_table(dictionary / "TSCharacters.txt"), {})
    args.output.write_text(
        HEADER
        + "# Pairs of characters: a Simplified-only character, then its Traditional form as Taiwan writes it.\n"
        + _constant("TO_TRADITIONAL", to_traditional)
        + "\n# Pairs of characters: a Traditional-only character, then its Simplified form.\n"
        + _constant("TO_SIMPLIFIED", to_simplified),
        encoding="utf-8",
    )
    print(f"{len(to_traditional) // 2} to Traditional, {len(to_simplified) // 2} to Simplified")


if __name__ == "__main__":
    main()
